spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file
server:
  port: 18082
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8761/eureka/,http://eureka-server3:8763/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true